export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const MY_ORDER_REQUEST = "MY_ORDER_REQUEST ";
export const MY_ORDER_SUCCESS = "MY_ORDER_SUCCESS";
export const MY_ORDER_FAIL = "MY_ORDER_FAIL";
export const MY_ORDER_RESET = "MY_ORDER_RESET";

export const ORDERS_REQUEST = "ORDERS_REQUEST ";
export const ORDERS_SUCCESS = "ORDERS_SUCCESS";
export const ORDERS_FAIL = "ORDERS_FAIL";
export const ORDERS_RESET = "ORDERS_RESET";

export const ORDERS_DELIVER_REQUEST = "ORDERS_DELIVER_REQUEST ";
export const ORDERS_DELIVER_SUCCESS = "ORDERS_DELIVER_SUCCESS";
export const ORDERS_DELIVER_FAIL = "ORDERS_DELIVER_FAIL";
export const ORDERS_DELIVER_RESET = "ORDERS_DELIVER_RESET";
